### ISSUE TITLE
generated wrong `src/pb/mod.rs` before creation

### ISSUE THREAD

**Issue by Pelotfr** [streamingfast/substreams-ethereum-quickstart#2]
When following the [quickstart guide](https://substreams.streamingfast.io/getting-started/quickstart), and using `substreams protogen`, the `src/pb/mod.rs` will be automatically generated with a different content than what the guide asks us to manually create.

By the way the given `substreams protogen` command is missing the `"` character at the end.

The generated `src/pb/mod.rs` will yield an unresolved import error when trying to build later.

Here are some screens to better understand:

Documentation: (with missing `"` and the content asked to create manually)
![image](https://github.com/streamingfast/substreams-ethereum-quickstart/assets/65423129/f2cc3c24-35b8-445e-8d2c-039f9ece3091)

Command output on my side:
![image](https://github.com/streamingfast/substreams-ethereum-quickstart/assets/65423129/5b6a3245-bd36-403b-8202-66981056ae19)

File `src/pb/mod.rs` generated after the command:
![image](https://github.com/streamingfast/substreams-ethereum-quickstart/assets/65423129/3e1dfc6c-d220-4fff-b8cd-bdf458ee2834)

Error prompted when trying to build:
![image](https://github.com/streamingfast/substreams-ethereum-quickstart/assets/65423129/593d43bb-40e3-4269-bd5e-e5eae3251305)

Package versions:
![image](https://github.com/streamingfast/substreams-ethereum-quickstart/assets/65423129/243134b8-e93c-45c0-8b3f-58e754ff92ca)

**Comment by maoueh** [comment]
Thanks, I've fixed everything and also updated https://github.com/streamingfast/substreams-ethereum-quickstart to use `substreams protogen` latest version which generates the `mod.rs` automatically now.

Let me know if anything else is not working properly.
